query Porfolios($slug: String) {
  portfolios(where: { slug: $slug }) {
    id
    slug
    title
    order
    description
    content
    url
    urlgithub
    phrasechoc
    technos {
      title
      id
      slug
      image {
        url
        size: formats
      }
    }
    image {
      url
      size: formats
    }
    images {
      url
      size: formats
    }
  }
}
