query PremPage {
  premierePage {
    headsite

    services {
      title
      content
      image {
        url
      }
      svg
    }
    presentation {
      title
      content
      image {
        url
        size: formats
      }
      svg
    }
    pitch {
      title
      content
      image {
        url
        size: formats
      }
      svg
    }
  }
}
